spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_next
    username: postgres
    password: pgpwd4
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  liquibase:
    change-log: classpath:db/changelog/changelog-root.yaml
#    enabled: false
